---

  - name: Check if terraform is installed
    command: terraform
    register: is_installed

  - name: Install Terraform if not installed
    include_role:
      name: terraform
    when: is_installed.stdout.find('command not found') != -1

  - name: Checkout infra code from Github
    git:
      repo: "git@github.com:{{ product }}/{{ gitlab_repo }}.git"
      dest: "{{ playbook_dir }}"
      version: v0.1.0

  - name: Terraform Action 
    terraform:
      project_path: "{{ playbook_dir }}/{{ gitlab_repo }}"
      targets: "{{ tf_resource_targets | default(omit) }}"
      state: "{{ lookup('env','STATE') | state }}"
      force_init: "{{ tf_force_init | default(omit) }}"
      variables: "{{ tf_vars }}"
